# -*- coding: utf-8 -*-
"""aRmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iG-Q4MY2SrhvcYW7qA1-e-Ag1iF5mlMe
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import classification_report, confusion_matrix

# UPDATE THIS TO YOUR SPECIFIC PATH
base_path = "/content/drive/MyDrive/finalaipro"

# --- 1. SETTINGS ---
IMG_SIZE = (224, 224)
BATCH_SIZE = 16
EPOCHS = 40  # Increased for fine-tuning potential

# --- 2. DATA AUGMENTATION (The "Force Multiplier") ---
# This is crucial for your small dataset of 500 images
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# Validation and Test should only be rescaled
val_test_datagen = ImageDataGenerator(rescale=1./255)

print("\n📦 Loading Datasets...")
train_gen = train_datagen.flow_from_directory(
    os.path.join(base_path, "train"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

val_gen = val_test_datagen.flow_from_directory(
    os.path.join(base_path, "validate"),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary"
)

test_gen = val_test_datagen.flow_from_directory(
    os.path.join(base_path, "test"),
    target_size=IMG_SIZE,
    batch_size=1, # One at a time for precise testing
    class_mode="binary",
    shuffle=False
)

# --- 3. THE MODEL (Transfer Learning) ---
#
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False  # Keep the "brain" frozen initially

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.BatchNormalization(), # Added for training stability
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

# --- 4. SMART CALLBACKS ---
my_callbacks = [
    callbacks.EarlyStopping(monitor='val_loss', patience=6, restore_best_weights=True),
    callbacks.ModelCheckpoint('ai_vs_real_best.h5', save_best_only=True)
]

# --- 5. INITIAL TRAINING ---
print("\n🚀 Stage 1: Training the Head...")
history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=EPOCHS // 2,
    callbacks=my_callbacks
)

# --- 6. STAGE 2: FINE-TUNING (To boost accuracy beyond 85%) ---
# We unfreeze the top layers of the base model to learn specific AI textures
print("\n🔓 Stage 2: Fine-Tuning...")
base_model.trainable = True
# Only train from the 100th layer onwards to avoid breaking the features
for layer in base_model.layers[:100]:
    layer.trainable = False

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5), # Tiny LR for fine-tuning
              loss='binary_crossentropy',
              metrics=['accuracy'])

history_finetune = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=10,
    callbacks=my_callbacks
)

# --- 7. EVALUATION ---
print("\n🔍 Final Evaluation on Test Set...")
test_gen.reset()
predictions = model.predict(test_gen)
y_pred = (predictions > 0.5).astype(int).flatten()
y_true = test_gen.classes

print("\n--- CLASSIFICATION REPORT ---")
print(classification_report(y_true, y_pred, target_names=['AI', 'Real']))

# --- 8. VISUALIZE RESULTS ---
#
def plot_results(h1, h2):
    acc = h1.history['accuracy'] + h2.history['accuracy']
    val_acc = h1.history['val_accuracy'] + h2.history['val_accuracy']

    plt.figure(figsize=(8, 5))
    plt.plot(acc, label='Total Training Acc')
    plt.plot(val_acc, label='Total Validation Acc')
    plt.axvline(x=len(h1.history['accuracy'])-1, color='r', linestyle='--', label='Fine-Tuning Start')
    plt.title('Accuracy Growth')
    plt.legend()
    plt.show()

plot_results(history, history_finetune)

import matplotlib.pyplot as plt
import numpy as np

# 1. Data Setup
labels = ['AI Generated', 'Real Image']
actual_counts = [46, 48]
predicted_counts = [55, 39]

x = np.arange(len(labels))  # Label locations
width = 0.35               # Width of the bars

# 2. Plotting
plt.figure(figsize=(10, 6))
bar1 = plt.bar(x - width/2, actual_counts, width, label='Actual (Ground Truth)',
               color='#3498db', alpha=0.9, edgecolor='black')
bar2 = plt.bar(x + width/2, predicted_counts, width, label='Model Predictions',
               color='#e67e22', alpha=0.9, edgecolor='black')

# 3. Aesthetics
plt.ylabel('Number of Images', fontsize=12, fontweight='bold')
plt.title('Actual Class vs. Model Predicted Distribution', fontsize=14, fontweight='bold')
plt.xticks(x, labels, fontsize=11)
plt.ylim(0, max(actual_counts + predicted_counts) + 12) # Leave space for text labels
plt.legend(frameon=True, shadow=True)
plt.grid(axis='y', linestyle='--', alpha=0.5)

# 4. Adding Value Labels on Top of Bars
def add_labels(rects):
    for rect in rects:
        height = rect.get_height()
        plt.annotate(f'{int(height)}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 5),  # 5 points vertical offset
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=11, fontweight='bold')

add_labels(bar1)
add_labels(bar2)

# 5. Adding a Mentorship Note (Explaining the gap)
plt.annotate('Model is "Paranoid":\nPredicting more AI than exists',
             xy=(0.18, 56), xytext=(0.5, 62),
             arrowprops=dict(facecolor='black', shrink=0.05, width=1),
             fontsize=10, bbox=dict(boxstyle="round", fc="0.9"))

plt.tight_layout()
plt.show() # Use plt.show() for immediate view in Google Colab

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# --- DATA FROM CLASSIFICATION REPORT ---
categories = ['Precision', 'Recall', 'F1-Score']
ai_metrics = [0.82, 0.98, 0.89]
real_metrics = [0.97, 0.79, 0.87]

x = np.arange(len(categories))
width = 0.35

# 1. Plotting the Metrics Bar Chart
plt.figure(figsize=(6, 6))
bar1 = plt.bar(x - width/2, ai_metrics, width, label='AI Generated', color='#3498db', alpha=0.8, edgecolor='black')
bar2 = plt.bar(x + width/2, real_metrics, width, label='Real Image', color='#2ecc71', alpha=0.8, edgecolor='black')

plt.ylabel('Score (0.0 - 1.0)', fontsize=12)
plt.title('Model Performance Metrics: AI vs. Real', fontsize=14, fontweight='bold')
plt.xticks(x, categories)
plt.ylim(0, 1.15)
plt.legend(loc='upper right')
plt.grid(axis='y', linestyle='--', alpha=0.5)

# Function to add values on top of bars automatically
def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        plt.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontweight='bold')

autolabel(bar1)
autolabel(bar2)

plt.tight_layout()
plt.show()

# 2. Confusion Matrix
# Correct Layout for Confusion Matrix:
# Row 0: Actual AI [True AI (TP), False Real (FN)]
# Row 1: Actual Real [False AI (FP), True Real (TN)]
cm = np.array([[45, 1],
               [10, 38]])

labels = ['AI Generated', 'Real Image']

plt.figure(figsize=(6, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels,
            square=True, cbar_kws={"shrink": .8},
            annot_kws={"size": 16, "weight": "bold"})

plt.xlabel('Predicted Label', fontsize=12, fontweight='bold')
plt.ylabel('True Label', fontsize=12, fontweight='bold')
plt.title('Confusion Matrix: Final Test Set', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.show()

import numpy as np
from google.colab import files
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# 1. Load your saved model
model = tf.keras.models.load_model('ai_vs_real_best.h5')

def test_new_image():
    uploaded = files.upload()

    for fn in uploaded.keys():
        # 2. Preprocessing
        img = image.load_img(fn, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0)
        img_array /= 255.0  # Crucial: Must match training normalization

        # 3. Prediction
        prediction = model.predict(img_array)[0][0]

        # 4. Result
        label = "REAL" if prediction > 0.5 else "AI"
        confidence = prediction if prediction > 0.5 else 1 - prediction

        plt.imshow(img)
        plt.title(f"Verdict: {label} ({confidence*100:.2f}%)")
        plt.axis('off')
        plt.show()

test_new_image()

import numpy as np
from google.colab import files
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# 1. Load your saved model
model = tf.keras.models.load_model('ai_vs_real_best.h5')

def test_new_image():
    uploaded = files.upload()

    for fn in uploaded.keys():
        # 2. Preprocessing
        img = image.load_img(fn, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0)
        img_array /= 255.0  # Crucial: Must match training normalization

        # 3. Prediction
        prediction = model.predict(img_array)[0][0]

        # 4. Result
        label = "REAL" if prediction > 0.5 else "AI"
        confidence = prediction if prediction > 0.5 else 1 - prediction

        plt.imshow(img)
        plt.title(f"Verdict: {label} ({confidence*100:.2f}%)")
        plt.axis('off')
        plt.show()

test_new_image()

import numpy as np
from google.colab import files
from tensorflow.keras.preprocessing import image
import matplotlib.pyplot as plt

# 1. Load your saved model
model = tf.keras.models.load_model('ai_vs_real_best.h5')

def test_new_image():
    uploaded = files.upload()

    for fn in uploaded.keys():
        # 2. Preprocessing
        img = image.load_img(fn, target_size=(224, 224))
        img_array = image.img_to_array(img)
        img_array = np.expand_dims(img_array, axis=0)
        img_array /= 255.0  # Crucial: Must match training normalization

        # 3. Prediction
        prediction = model.predict(img_array)[0][0]

        # 4. Result
        label = "REAL" if prediction > 0.5 else "AI"
        confidence = prediction if prediction > 0.5 else 1 - prediction

        plt.imshow(img)
        plt.title(f"Verdict: {label} ({confidence*100:.2f}%)")
        plt.axis('off')
        plt.show()

test_new_image()

